
	LogoTD[0] = TextDrawCreate(537.0001, 2.7629, "LD_BEAT:chit");
	TextDrawLetterSize(LogoTD[0], 0.0, 0.0);
	TextDrawTextSize(LogoTD[0], 32.0, 37.0);
	TextDrawColor(LogoTD[0], -1322626305);
	TextDrawFont(LogoTD[0], 4);

	LogoTD[1] = TextDrawCreate(548.3333, 13.7036, "Montana");
	TextDrawLetterSize(LogoTD[1], 0.4, 1.6);
	TextDrawColor(LogoTD[1], -206429953);
	TextDrawFont(LogoTD[1], 1);
	TextDrawSetShadow(LogoTD[1], 0);

	LogoTD[2] = TextDrawCreate(561.9999, 0.2740, "LD_BEAT:chit");
	TextDrawLetterSize(LogoTD[2], 0.0, 0.0);
	TextDrawTextSize(LogoTD[2], 17.0, 18.0);
	TextDrawColor(LogoTD[2], -919319809);
	TextDrawFont(LogoTD[2], 4);

	LogoTD[3] = TextDrawCreate(578.1661, 6.4962, "LD_BEAT:chit");
	TextDrawLetterSize(LogoTD[3], 0.0, 0.0);
	TextDrawTextSize(LogoTD[3], 11.0, 12.0);
	TextDrawColor(LogoTD[3], -730515969);
	TextDrawFont(LogoTD[3], 4);
